# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mm < Formula
  desc "Mattermost CLI for humans and agents"
  homepage "https://github.com/ayusavin/mattermost-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.2/mm_0.1.2_darwin_amd64.tar.gz"
      sha256 "fdb6abddf14a77d0d097398b1d431304bf859ee84e7650ac946b6ead5d0f85cd"

      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.2/mm_0.1.2_darwin_arm64.tar.gz"
      sha256 "6a09399080c6eecf6bdaddd08f71a03664ae5eddc2ead7969fe39ea04dd392d5"

      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.2/mm_0.1.2_linux_amd64.tar.gz"
      sha256 "5504de3344131249cee9b7facaac2ff2960714330ba55bf259c42a06e4c041e0"
      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.2/mm_0.1.2_linux_arm64.tar.gz"
      sha256 "8ce6041eaaaa2d1eb7e833530097da9770b9b6332f7f8e76a7bddd3a602ca601"
      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
  end

  test do
    system "#{bin}/mm", "--version"
  end
end
