# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mm < Formula
  desc "Mattermost CLI for humans and agents"
  homepage "https://github.com/ayusavin/mattermost-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.0/mm_0.1.0_darwin_amd64.tar.gz"
      sha256 "4be7b0719e5fa8a7d1a02b3436ba1d3f73b930bf5d562827bb55770c3234b970"

      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.0/mm_0.1.0_darwin_arm64.tar.gz"
      sha256 "0a082c1bde01ede42994372316c8e38270551cc329df12d68e57a6c4ae98a18e"

      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.0/mm_0.1.0_linux_amd64.tar.gz"
      sha256 "a32394e4db726a997d387e2a4a7db058128a2d1b2748f50c9dd5e885c458e033"
      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayusavin/mattermost-cli/releases/download/v0.1.0/mm_0.1.0_linux_arm64.tar.gz"
      sha256 "4b5341faeab1adf0946eda90e88d319fc9bc03de7e9f11c3a8b31d20380994f7"
      define_method(:install) do
        bin.install "mm"
        generate_completions_from_executable(bin/"mm", "completion")
      end
    end
  end

  test do
    system "#{bin}/mm", "--version"
  end
end
